baseUri=http\://localhost\:3000/api/v1

approvedSellerEmail=dragan.seed@kuvam.rs
approvedSellerPassword=Test1234

approvedSeller2Email=jelena.seed@kuvam.rs
approvedSeller2Password=Test1234

pendingSellerEmail=marija.pending@kuvam.rs
pendingSellerPassword=Test1234

suspendedUserEmail=ana.suspended@kuvam.rs
suspendedUserPassword=Test1234

bannedUserEmail=luka.banned@kuvam.rs
bannedUserPassword=Test1234

buyerEmail=nikola.seed@kuvam.rs
buyerPassword=Test1234

buyer2Email=sofija.seed@kuvam.rs
buyer2Password=Test1234

userPasswordChangeEmail=milica.seed@kuvam.rs
userPasswordChangePassword=Test1234

deactivatedUserEmail=jovana.deactivated@kuvam.rs
deactivatedUserPassword=Test1234


rejectedUserEmail=ivana.rejected@kuvam.rs
rejectedUserPassword=Test1234

adminEmail=admin@kuvam.rs
adminPassword=qwertyuiopasdfghjklzxcvbnm1234567890